# Exported from Render on 2024-10-26T17:19:40Z
services:
- type: web
  name: JavaScript-Lab
  runtime: node
  repo: https://github.com/oomeanujoo/JavaScript-Lab
  plan: free
  envVars:
  - key: DB_PASSWORD
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_URL
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: npm start
version: "1"
